acuatica/urls.py
# coding=utf-8
from django.conf.urls import url, include
from django.urls import path

from acuatica import views


urlpatterns = [
    url(r'^$', views.index_view, name='acuatica.index'),
    url(r'^login/$', views.login_view, name='acuatica.login'),
    url(r'^register/$', views.register_view, name='acuatica.register'),
    url(r'^logout/$', views.logoutUser, name='acuatica.logout'),
    url(r'^venta-normal/$', views.SalesView.as_view(), name='acuatica.sales.view'),
    url(r'^venta-normal-add/$', views.sales, name='acuatica.sales'),
    url(r'^clientes/$', views.clients, name='acuatica.clientes'),
    url(r'^catalogo/$', views.catalogo, name='acuatica.catalogo'),
    url(r'^entradas/$', views.inputs, name='acuatica.inputs'),
    url(r'^reporte-ventas/$', views.sales_report, name='acuatica.sales-report'),
    url(r'^reporte-ventas2/$', views.sales_report2, name='acuatica.sales-report2'),
    url(r'^inv-save/$', views.inv_save, name='acuatica.inv-save'),
    url(r'^sales-charge/$', views.sales_charge, name='acuatica.sales-charge'),
    url(r'^sale-ticket/$', views.ticket, name='acuatica.sales-ticket'),
    url(r'^new-sidebar/$', views.new_sidebar, name='acuatica.new-sidebar'),
    url(r'^cancela-venta/(?P<pk>\d+)/$',
        views.cancel_sale, name='acuatica.cancel-sale'),
]

urioste/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'acuatica/', include('acuatica.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

acuatica/models.py
from django.db import models
from django.contrib.auth.models import User
from multiselectfield import MultiSelectField
from django.db.models import Sum
from django.db.models.signals import post_save, post_delete
from django.utils.translation import ugettext_lazy as _


class UserExtends(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,
                             related_name='user_extend', verbose_name='usuario')
    name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    is_admin = models.BooleanField(default=False)

    class Meta(object):
        verbose_name_plural = 'Usuario'
        permissions = {
            ('is_cashier', _('Es cajero')),
            ('is_admin', _('Es admin')),
        }

    def __str__(self):
        return str(self.name)


class Levels(models.Model):
    level = models.CharField(max_length=100)

    def __str__(self):
        return str(self.level)


class Clients(models.Model):
    MALE = 'M'
    FEMALE = 'F'
    SEX_CHOICE = (
        (MALE, 'Hombre'),
        (FEMALE, 'Mujer')
    )

    SINGLE = 'S'
    MARRIED = 'M'
    DIVORCE = 'D'
    FREE = 'F'
    CIVIL_CHOICE = (
        (SINGLE, 'Soltero'),
        (MARRIED, 'Casado'),
        (DIVORCE, 'Divorsiado'),
        (FREE, 'Union libre')
    )

    FACEBOOK = 'F'
    RECOMANDATION = 'R'
    TRANSIT = 'T'
    OTHER = 'F'
    FIND_CHOICES = (
        (FACEBOOK, 'Facebook'),
        (RECOMANDATION, 'Recomendacion'),
        (TRANSIT, 'Transito'),
        (OTHER, 'Otro')
    )

    name = models.CharField(max_length=50)
    #picture = models.ImageField(verbose_name='foto', null=True, blank=True)
    image_source = models.TextField()
    last_name = models.CharField(max_length=50)
    second_last_name = models.CharField(max_length=50)
    birth_date = models.DateField(blank=True, null=True)
    gender = models.CharField(choices=SEX_CHOICE, max_length=10)
    address = models.CharField(max_length=200)
    suburb = models.CharField(max_length=200)
    postal_code = models.CharField(max_length=10)
    cel = models.CharField(max_length=12)
    email = models.EmailField(blank=True, null=True)
    civil_status = models.CharField(max_length=10, choices=CIVIL_CHOICE)
    heard_from = models.CharField(max_length=10, choices=FIND_CHOICES)
    blood = models.CharField(max_length=50)
    emergency_contact = models.CharField(max_length=200)
    emergency_phone = models.CharField(max_length=20)
    pay_day = models.CharField(max_length=200)
    medical_condition = models.TextField()
    schedule = models.TextField()
    level = models.ForeignKey(Levels, on_delete=models.DO_NOTHING)

    class Meta(object):
        verbose_name_plural = 'Clientes'

    def __str__(self):
        return str(self.name)


class Inventario(models.Model):
    BIG = 'B'
    MEDIUM = 'M'
    SMALL = 'S'
    SIZE_CHOICE = (
        (BIG, 'Grande'),
        (MEDIUM, 'Mediano'),
        (SMALL, 'Chico'),

    )

    ACUATICA = 'A'
    AJUSTES_CONTABLES = 'AJ'
    MANTENIMIENTO = 'M'
    TIENDITA = 'T'
    BRANCH_CHOICES = (
        (ACUATICA, 'Acuatica Urioste'),
        (AJUSTES_CONTABLES, 'Ajustes Contables'),
        (MANTENIMIENTO, 'Mantenimineto'),
        (TIENDITA, 'Tiendita'),
    )

    numcode = models.CharField(max_length=100)
    # categoria A
    # categoria B
    name = models.CharField(max_length=100, unique=True)
    visible = models.BooleanField(default=True)
    size = models.CharField(max_length=20, choices=SIZE_CHOICE, default="0000")
    measures = models.CharField(
        max_length=200, default="medidas para algunos productos")
    # descripcion cuadro bien complejo, creo que seria mejor hacerlo en el front end
    short_name = models.CharField(max_length=60, default="nombrecorto")
    branches = MultiSelectField(
        choices=BRANCH_CHOICES, blank=True, null=True, default=1)
    limited_inventory = models.BooleanField(default=True)
    contained_products = models.CharField(
        max_length=50, default="ProductosContenidos")
    minimum_amount = models.CharField(max_length=200)
    max_amount = models.CharField(max_length=100)
    colors = models.CharField(max_length=100, default="colores")
    browserdescription = models.CharField(
        max_length=100, default="descripcionBuscador")
    browserTitle = models.CharField(max_length=50, default="tituloBrowser")
    friendly_url = models.CharField(max_length=100, default="url")
    cost = models.IntegerField(default=0)
    total_cuantity = models.IntegerField(default=0)
    picture = models.ImageField(upload_to='images/', blank=True, null=True)

    class Meta(object):
        verbose_name_plural = 'Inventario'

    def __str__(self):
        return self.name


class Inputs(models.Model):
    inventario = models.ForeignKey(Inventario, on_delete=models.DO_NOTHING)
    cuantity = models.IntegerField()
    date = models.DateField(auto_now_add=True)
    sale = models.IntegerField()
    comments = models.TextField()

    class Meta(object):
        verbose_name_plural = 'Entradas y Salidas'

    def __str__(self):
        return self.inventario.name


def update_total_cuantity(sender, instance, **kwargs):
    count = instance.inventario.inputs_set.all().aggregate(Sum("cuantity"))
    instance.inventario.total_cuantity = count.get('cuantity__sum')
    instance.inventario.save()


def update_total_cuantity_sale(sender, instance, **kwargs):
    count = instance.inventario.inputs_set.all().aggregate(Sum("sale"))
    instance.inventario.total_cuantity -= count.get('sale__sum')
    instance.inventario.save()


post_save.connect(update_total_cuantity, sender=Inputs)
post_delete.connect(update_total_cuantity, sender=Inputs)
post_save.connect(update_total_cuantity_sale, sender=Inputs)
post_delete.connect(update_total_cuantity_sale, sender=Inputs)


class Sales(models.Model):
    TERMINADO = 'T'
    CANCELADO = 'C'
    STATUS_CHOICE = (
        (TERMINADO, 'Terminado'),
        (CANCELADO, 'Cancelado'),
    )
    user = models.ForeignKey(User, related_name='cajero',
                             on_delete=models.DO_NOTHING)
    client = models.ForeignKey(Clients, on_delete=models.DO_NOTHING)
    cash = models.FloatField()
    total = models.FloatField()
    discount = models.FloatField()
    charge = models.IntegerField()
    payForm = models.CharField(max_length=100)
    comments = models.TextField(blank=True, null=True)
    status = models.CharField(
        max_length=20, choices=STATUS_CHOICE, default=TERMINADO)
    created = models.DateField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = 'Ventas'

    def __str__(self):
        return self.user.username


class InvSales(models.Model):
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    inventory = models.ForeignKey(Inventario, on_delete=models.DO_NOTHING)
    sales = models.ForeignKey(Sales, on_delete=models.DO_NOTHING)
    quantity = models.IntegerField()
    created = models.DateField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = 'Cobros'

    def __str__(self):
        return self.user.username

acuatica/forms.py
# coding: utf-8
from django import forms
from django.contrib.admin.widgets import AutocompleteSelect
from django.contrib.auth.models import User
from django.contrib import admin
from django.contrib.admin.widgets import AdminDateWidget
from datetime import datetime
from acuatica.models import Inventario, Inputs, Clients
from django.contrib.auth.forms import UserCreationForm


class StylishForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs.update({'class': 'form-control'})


class LoginForm(forms.Form):
    user = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Usuario'}))
    password = forms.CharField(label='Contraseña',
                               widget=forms.PasswordInput(
                                   attrs={'class': 'form-control',
                                          'placeholder': 'Contraseña'}))


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class InputsForm(forms.ModelForm):
    class Meta:
        model = Inputs
        fields = ('inventario',)
        widgets = {
            'inventario': AutocompleteSelect(
                Inputs._meta.get_field('inventario').remote_field,
                admin.site,
                attrs={'placeholder': 'Seleccionar...',
                       'class': 'form-control'},
            )
        }


class InventarioForm(StylishForm):

    class Meta:
        model = Inventario
        fields = '__all__'


class InventoryForm(StylishForm):

    class Meta:
        model = Inventario
        fields = '__all__'


class ClientsForm(StylishForm):

    class Meta:
        model = Clients
        fields = '__all__'

acuatica/templates/acuatica/_messages.html
{% if messages %}
    <div class="row dj-messages">
    <div class="col-md-6 col-md-offset-3">
        {% for message in messages %}
            {% if message.tags == 'error' %}
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
            {% else %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            {% endif %}
            <strong>{{ message }}</strong>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endfor %}
        </div>
        {% if form.errors %}
                {% for field in form %}
                    {% for error in field.errors %}
                        <div class="alert alert-danger" role="alert">
                            <strong>{{ error|escape }}</strong>
                        </div>
                    {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                    <div class="alert alert-danger" role="alert">
                        <strong>{{ error|escape }}</strong>
                    </div>
                {% endfor %}
            {% endif %}
    </div>
{% endif %}

acuatica/templates/acuatica/base.html
{% load static %}
<!DOCTYPE html>

<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'styles/base.css' %}"></link>
    <link rel="stylesheet" href="{% static 'styles/new_sidebar.css' %}"></link>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous"/>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'admin/css/vendor/select2/select2.css' %}">
    <link rel="stylesheet" href="{% static 'admin/css/autocomplete.css' %}">
    <script type="text/javascript" src="https://unpkg.com/webcam-easy/dist/webcam-easy.min.js"></script>
</head>
    {% block site_css %}
    
    {% endblock %}    
    
    {% block site_js %}     
    {% endblock %}
    <script src="{% static 'admin/js/vendor/jquery/jquery.js' %}"></script>    
    <script src="{% static 'admin/js/vendor/select2/select2.full.js' %}"></script>
    <script src="{% static 'admin/js/jquery.init.js' %}"></script>
    <script src="{% static 'scripts/base.js' %}"></script>
    <script src="{% static 'scripts/side_bar.js' %}"></script>    
    <script src="{% static 'admin/js/autocomplete.js' %}"></script>    
    
    <title>{% block title %}{% endblock %}</title>
  </head>
  <body id="body-pd">
    
      {% include 'acuatica/_messages.html' %}
    
    <!-- End of Navigation Bar -->
      {% block content %} {% endblock %}
    
  </body>
</html>

acuatica/templates/acuatica/catalogo.html
{% extends 'acuatica/venta_normal.html' %} {% load static %} {% block title %}
Catalogo {% endblock %} {% block right_content %}
<div class="panel-derecho">
  <nav class="navbar navbar-expand-lg navbar-light bg-light" style="padding: 0">
    <div class="container-fluid" style="padding: 4px 15px 4px 15px">
      <p style="margin-right: 20px">Catalogo</p>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0"></ul>
        <form class="d-flex">
          {% csrf_token %}
          <input class="form-control me-2" list="datalistCatalogOptions" id="catalogDataList"
            placeholder="Buscar Producto" aria-label="Search" autocomplete="off" name="inventory" />
          <datalist id="datalistCatalogOptions">
            {% for i in inventory %}
            <option value="{{i.name}}"></option>
            {% endfor %}
          </datalist>
        </form>
      </div>
    </div>
  </nav>
  {% if inv %}
  <div class="card text-white bg-secondary m-4" style="max-width: 18rem">
    <div class="card-header" style="background:#0e1837">{{inv.name}}</div>
    <div class="card-body" style="background:#0e1837">
      <h5 class="card-title"></h5>
      <p class="card-text">Costo: {{inv.cost}}</p>
      <p class="card-text">Cantidad: {{inv.total_cuantity}}</p>
      <button type="button" class="btn btn-light" data-bs-toggle="modal" data-bs-target="#updatecatalogModal"
        data-bs-whatever="@mdo" onclick="hide()">
        Actualizar
      </button>

    </div>
  </div>
  {% endif %}
</div>
<script>
  function hide() {
    const visi = document.getElementById('id_visible');
    visi.style.display = "none";
    const size = document.getElementById('id_size');
    size.style.display = "none";
    const measures = document.getElementById('id_measures');
    measures.style.display = "none";
    const branches = document.getElementById('id_branches');
    branches.style.display = "none";
    const li = document.getElementById('id_limited_inventory');
    li.style.display = "none";
    const lo = document.getElementById('id_contained_products');
    lo.style.display = "none";
    const co = document.getElementById('id_colors');
    co.style.display = "none";
    const bo = document.getElementById('id_browserdescription');
    bo.style.display = "none";
    const to = document.getElementById('id_browserTitle');
    to.style.display = "none";
    const url = document.getElementById('id_short_name');
    url.style.display = "none";
  }
</script>
{% endblock %}

acuatica/templates/acuatica/reporte-ventas.html
{% extends "acuatica/acuatica.html" %} {% load static %} {% block title%}
Ventas{% endblock %}
 
{%block right_content %}
<div class="panel-derecho">
  <form action="{% url 'acuatica.sales-report' %}" method="post">
    {% csrf_token %}
  <nav class="navbar navbar-expand-lg navbar-light bg-light" style="padding: 0">
    <div class="container-fluid" style="padding: 4px 15px 4px 15px">
      <p style="margin-right: 20px">Reportes</p>
      <button
        class="navbar-toggler"
        type="button"
        data-bs-toggle="collapse"
        data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li style="margin-right:20px ;">
            <label for="folio">Folio</label>
            <input class="form-control" id="folio" name="folio" placeholder="Folio" autocomplete="off">
          </li>
          <li style="margin-right: 20px">
            <label for="reporteClienteDataList" class="form-label"
              >Cliente:</label
            >
            <input
              class="form-control"
              list="reporteclientelistOptions"
              id="client"
              name="client"
              placeholder="Cliente..."
              autocomplete="off"
            />
            <datalist id="reporteclientelistOptions">
              {% for sale in sales %}
              <option value="{{sale.client.id}}">{{ sale.client }}</option>              
              {% endfor %}
            </datalist>
          </li>
          <li class="nav-item" style="margin-right: 20px">
            <label for="cantidadventa" class="form-label">Estado:</label>
            <input
              class="form-control"
              id="status"
              name="status"
              list="estadoReportes"
              placeholder="estatus..."
              autocomplete="off"
            />
            <datalist id="estadoReportes">
              <option value="T"></option>
              <option value="C"></option>
            </datalist>
          </li>
          <li class="nav-item" style="margin-right: 20px">
            <label for="realizoventa" class="form-label">Realizò:</label>
            <input
              class="form-control"
              list="realizoventa"
              id="user"
              name="user"
              placeholder="Cliente..."
              autocomplete="off"
            />
            <datalist id="realizoventa">
              {% for sale in sales %}
              <option value="{{sale.user.id}}">{{ sale.user }}</option>              
              {% endfor %}
            </datalist>
          </li>
          <li class="nav-item" style="margin-right: 20px">
            <label for="formaPago" class="form-label">Fecha:</label>
            <input
              type="date"
              name="init_date"
              class="form-control"
              id="init_date"
              autocomplete="off"              
            />
          </li>
          <li class="nav-item" style="margin-right: 20px;">
            <button type="button"
            type="button"
                class="btn btn-dark mt-4"
                data-bs-toggle="modal"
                data-bs-target="#periodo"
                data-bs-whatever="@mdo"
                style="font-size: 15px"
            >Periodo de Tiempo</button>
          </li>
          
          
          
          
        </ul>        
          <button
            type="submit"
            class="btn btn-dark"
            data-bs-toggle="modal"
            data-bs-whatever="@mdo"
            style="font-size: 12px"
          >
            Buscar
          </button>        
      </div>      
    </div>
  </nav>
  </form>
  <div class="container2">
    <p class="font-weight-bold ml-2" style="font-size:20px;">Total: ${{total.total__sum}}</p>
    <table class="table table-light table-striped table-hover">
      <tbody>
        <tr>
          <td class="font-weight-bold">Folio</td>
          <td class="font-weight-bold">Realizó Venta</td>
          <td class="font-weight-bold">Cliente</td>
          <td class="font-weight-bold">Estatus</td>
          <td class="font-weight-bold">Caja</td>
          <td class="font-weight-bold">Tipo de Pago</td>
          <td class="font-weight-bold">Total</td>
          <td class="font-weight-bold">Fecha</td>
        </tr>
        {% for sale in sales %}
          <tr>
            <td>{{sale.id}}</td>
            <td>{{sale.user}}</td>
            <td>{{sale.client}}</td>
            <td>{{sale.status}}</td>
            <td>${{sale.cash}}</td>
            <td>{{sale.payForm}}</td>
            <td>${{sale.total}}</td>
            <td>{{sale.created}}</td>
            {% if sale.status == 'T'%}
            <td><a href="{% url 'acuatica.cancel-sale' pk=sale.pk %}" type="button">Cancelar</a></td>
            {% endif %}
            <!--<td><button type="button"
              class="btn btn-primary"
              data-bs-toggle="modal"
              data-bs-target="#cancelar"
              data-bs-whatever="@mdo" >Cancelar Venta</button></td>>-->
            {% for detail in sale.invsales_set.all %}          
            <tr>
              <td>{{detail.inventory}}</td>
              <td>{{detail.quantity}}</td>
            </tr>          
            {% endfor %}
            <tr>
              <td>Comentario: </td>
              <td>{{sale.comments}}</td>

            </tr>          
          </tr>
          {% endfor %}
      </tbody>
    </table>
  </div> 
  
</div>
<style>
  .container2 {
    box-shadow: 4px 0px 0px 8px rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
  -webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2),
    0 6px 20px 0 rgba(0, 0, 0, 0.19);
  -moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2),
    0 6px 20px 0 rgba(0, 0, 0, 0.19);
  }
</style>
{% endblock%}

acuatica/templates/acuatica/reporte-ventas2.html
{% extends "acuatica/acuatica.html" %} {% load static %} {% block title%}
Ventas{% endblock %}

{%block right_content %}
<div class="container mt-5">
    <form action="{% url 'acuatica.sales-report2' %}" method="POST">
        {% csrf_token %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light" style="background-color:#e3f2fd">
        <div class="container-fluid" style="padding: 4px 15px 4px 15px">

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li style="margin-right:20px ;">
                        <label for="folio">Folio</label>
                        <input class="form-control" id="folio" name="folio" placeholder="Folio" autocomplete="off">
                    </li>
                    <li style="margin-right: 20px">
                        <label for="reporteClienteDataList" class="form-label">Cliente:</label>
                        <input class="form-control" list="reporteclientelistOptions" id="client" name="client"
                            placeholder="Cliente..." autocomplete="off" />
                        <datalist id="reporteclientelistOptions">
                            {% for sale in sales %}
                            <option value="{{sale.client.id}}">{{ sale.client }}</option>
                            {% endfor %}
                        </datalist>
                    </li>
                    <li class="nav-item" style="margin-right: 20px">
                        <label for="cantidadventa" class="form-label">Estado:</label>
                        <input class="form-control" id="status" name="status" list="estadoReportes"
                            placeholder="estatus..." autocomplete="off" />
                        <datalist id="estadoReportes">
                            <option value="T"></option>
                            <option value="C"></option>
                        </datalist>
                    </li>
                    <li class="nav-item" style="margin-right: 20px">
                        <label for="realizoventa" class="form-label">Realizò:</label>
                        <input class="form-control" list="realizoventa" id="user" name="user" placeholder="Cajero..."
                            autocomplete="off" />
                        <datalist id="realizoventa">
                            {% for sale in sales %}
                            <option value="{{sale.user.id}}">{{ sale.user }}</option>
                            {% endfor %}
                        </datalist>
                    </li>
                    <li class="nav-item" style="margin-right: 20px">
                        <label for="formaPago" class="form-label">Fecha:</label>
                        <input type="date" name="init_date" class="form-control" id="init_date" autocomplete="off" />
                    </li>
                    <li class="nav-item" style="margin-right: 20px;">
                        <button type="button" type="button" class="btn btn-dark mt-4" data-bs-toggle="modal"
                            data-bs-target="#periodo" data-bs-whatever="@mdo" style="font-size: 15px">Periodo de
                            Tiempo</button>
                    </li>




                </ul>
                <button type="submit" class="btn btn-dark" data-bs-toggle="modal" data-bs-whatever="@mdo"
                    style="font-size: 12px">
                    Buscar
                </button>
            </div>
        </div>
    </nav>
</form>
</div>
<div class="container mt-2">
    <div class="row">


        <div class="col-md-12">
            <h4>Reporte de ventas: ${{total.total__sum}}</h4>
            <div class="table-responsive">


                <table id="mytable" class="table table-bordred table-striped">

                    <thead>
                        <th class="font-weight-bold">Folio</th>
                        <th class="font-weight-bold">Realizó</th>
                        <th class="font-weight-bold">Cliente</th>
                        <th class="font-weight-bold">Estatus</th>
                        <th class="font-weight-bold">Caja</th>
                        <th class="font-weight-bold">Tipo de Pago</th>
                        <th class="font-weight-bold">Total</th>
                        <th class="font-weight-bold">Fecha</th>
                    </thead>
                    <tbody>

                        {% for sale in sales %}
                        <tr>

                            <td>{{sale.id}}</td>
                            <td>{{sale.user}}</td>
                            <td>{{sale.client}}</td>
                            <td>{{sale.status}}</td>
                            <td>${{sale.cash}}</td>
                            <td>{{sale.payForm}}</td>
                            <td>${{sale.total}}</td>
                            <td>{{sale.created}}</td>
                            <td>
                                <p data-placement="top" data-toggle="tooltip" title="Delete"><a href="{% url 'acuatica.cancel-sale' pk=sale.pk %}" type="button">Cancelar</a>
                                </p>
                            </td>
                        </tr>
                        {% for detail in sale.invsales_set.all %}
                        <tr>
                            <td>{{detail.inventory}}</td>
                            <td>{{detail.quantity}}</td>

                        </tr>
                        {% endfor %}
                        <tr>
                            <td>Comentario: </td>
                            <td>{{sale.comments}}</td>

                        </tr>


                        {% endfor %}
                    </tbody>

                </table>
            </div>
            {% endblock%}